version: '3'

services:

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - .:/var/www

  nginx:
    build:
      context: docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - 1122:80